### ISSUE TITLE
Problem with 2.7.0 on Gotham? 

### ISSUE THREAD

**Issue by tknorris** [Eldorados/script.module.urlresolver#261]
See [this thread](http://forums.tvaddons.ag/threads/29914-Error-while-trying-to-resolve) for an issue w/ trying to load resolvers in 2.7 on Gotham on Windows. From the thread it appears that the new loader isn't working for him since 2.6 works fine.

I think what's happening is an ImportError is getting thrown again and again, though I'm not at all sure why. @VioletRed maybe you can take a look at this to try to debug the issue?

**Comment by tknorris** [comment]
I wonder if it's significant that it fails on the youtube resolver each time....

**Comment by VioletRed** [comment]
The kind of error that shows in the log happens if you have modules with duplicated names.

My first guess is a problem during update, but he did forced a re-install already. This line, however makes me wonder:

> I've made a backup of the version 2.6 folder, just in case.

How did he do the backup? If he just copied directory "script.module.urlresolver" to "script.module.urlesolver-2.6"  or something like that in ./xbmc/addons folder, it might happen that python includes it in the path, causing the confusion at loading time.

I don't have a Gotham installation anymore, so I can't test myself. Can you ask him? Or test yourself?

**Comment by tknorris** [comment]
I don't have a Gotham install anymore either so I can't test it either. In terms of the duplicate module thing I don't think it would be being caused by multiple plugin dirs only because line 11138 of the log shows it only loading one directory. Also, I think he only made the 2.6.0 copy after having the problem and 2.6.0 solved it for him.

**Comment by VioletRed** [comment]
The directory used for scanning doesn't have to be the same from where the module is actually loaded. The scope in python can do weird things some times.

Module loading is just equivalent to
```import modulename```
It means that the scan process might reference one directory, but the loading happening from another one that happens to appear first in the path.

I'm trying to reproduce the error, and be back to you.

**Comment by tknorris** [comment]
You make a good point. So, what could be happening then is youtube.py exists in one of the other path directories and is being imported rather than the resolver youtube.py which then throws the importerror again and again resulting in that log spamming....

**Comment by VioletRed** [comment]
Maybe adding the plugins dir at the beginning of the path would help?

```diff
diff --git a/lib/urlresolver/plugnplay/__init__.py b/lib/urlresolver/plugnplay/__init__.py
index c123bbb..d4c849f 100644
--- a/lib/urlresolver/plugnplay/__init__.py
+++ b/lib/urlresolver/plugnplay/__init__.py
@@ -167,7 +167,7 @@ def load_plugin(mod):
 
 def load_plugins():
     for d in plugin_dirs:
-        sys.path.append(d)
+        sys.path.insert(0, d)
         py_files = glob(join(d, '*.py'))
 
         # Remove ".py" for proper importing
@@ -179,7 +179,7 @@ def load_plugins():
 def scan_plugins(wrappercls):
     re_class = re.compile('class\s+(\w+).*Plugin')
     for d in plugin_dirs:
-        sys.path.append(d)
+        sys.path.insert(0, d)
         py_files = glob(join(d, '*.py'))
         for f in py_files:
             found_plugin = None
```

**Comment by tknorris** [comment]
I haven't the foggiest idea what will solve it. ;-)

Maybe you should reply to the guy in the thread and see if he'll help you try different solutions by dropping your patched py files into urlreoslver? From his responses he seemed pretty competent.

Also, if we think it's picking up an alternate youtube.py from elsewhere in the path, maybe you could have him uninstall the addons listed in the path one by one to see if it fixes the problem. Then at least we'll know how to reproduce it. (i.e. just install that addon)

**Comment by VioletRed** [comment]
It seems that I deleted my previous post, but I just found the bug that causes the ImportError re-triggering. A patch in b9dc9c845ced23a5414ae6562d3166ace198d8e6, and the patch for 2.7.0 2eae59c88ae9c4874c0084873e894c6dcde299ea. 

It should control the error, but still won't make his youtube plugin work. I'll try to contact the user and see what we can do.

**Comment by tknorris** [comment]
The commit doesn't really explain what's going wrong. Out of curiosity, can you elaborate? Will youtube only not work in that situation or at all? Why?

**Comment by VioletRed** [comment]
I included some comments in the b9dc9c845ced23a5414ae6562d3166ace198d8e6, but besides that, the problem seems to be quite hard to track. It can only occur if 1) load_module() succeeds, and 2) the loaded module is not usable.

The only situation when i found it before is with modules with duplicated names. In such situation PluginMeta (plugnplay.py@126) would load the first one properly, but the second one would replace the first one because plugins are tracked by name (line 137), what would leave the second implementor "not_implemented()"

It to my mind that it will also happen if the plugin doesn't include a `implements = [UrlResolver, PluginSettings]` line. In that case PluginMeta won't be called either and the implementor would be empty even if load_module() succeeded.

**Comment by tknorris** [comment]
In SALTS, I use [this method](https://github.com/tknorris/salts/blob/master/salts_lib/utils.py#L485) of determining all the implementors of a given abstract parent class. Would that method work in this case? If so, would it be more reliable? I've never dove into why urlresolver has all that class loading logic, but I have the same basic thing in SALTS but it's implemented so much simpler.

**Comment by VioletRed** [comment]
> Would that method work in this case? If so, would it be more reliable?

I'll take a look. Simpler is better.

>  I've never dove into why urlresolver has all that class loading logic.

It uses a general solution from https://github.com/daltonmatos/plugnplay, that's why.

> On your last comment, that would also be true if the "import youtube" was importing the wrong class that didn't have an implements list.

Yes, that's the intended fix with the first patch. If the plugins directory appears first in the path, it won't load other modules by mistake.
