### ISSUE TITLE
streamcloud.eu link false since Upadate 2.8.0

### ISSUE THREAD

**Issue by Ltownwriter** [Eldorados/script.module.urlresolver#267]
09:56:29 T:1809839120  NOTICE:     [PLUGIN] xStream->burning_series_org: http://www.burning-seri.es/serie/Arrow/1/17-Die-Raecherin/Streamcloud-1
09:56:30 T:1809839120  NOTICE: URLResolver: Initializing URLResolver version: 2.8.0
09:56:30 T:1809839120  NOTICE: URLResolver: Update settings from  to 2.8.0
09:56:32 T:1809839120  NOTICE:     [PLUGIN] xStream->burning_series_org: call play: http://streamcloud.eu/sj2c8fqxfa3k/Arrow.S01E17.Die.Raecherin.GERMAN.DUBBED.BDRip.XviD-HQSD.avi.html
09:56:32 T:1809839120  NOTICE:     [PLUGIN] xStream->burning_series_org: File link: False
09:56:32 T:1809839120  NOTICE: Fals

The link is correct and the file online.

Its with all streamcloud links.

**Comment by RomanOnymous** [comment]
How can I get streamcloud.eu working again? As far as I see, there is already a forked solution.. Will there be a 2.8.1 update soon?

**Comment by Eldorados** [comment]
Yes, just wait for the release                                                                                                                                                                                                                                                                          Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                                         From: RomanOnymousSent: Saturday, February 28, 2015 6:44 AMTo: Eldorados/script.module.urlresolverReply To: Eldorados/script.module.urlresolverSubject: Re: [script.module.urlresolver] streamcloud.eu link false since Upadate 2.8.0 (#267)How can I get streamcloud.eu working again? As far as I see, there is already a forked solution.. Will there be a 2.8.1 update soon?

—Reply to this email directly or view it on GitHub.
